[build]
  publish = "."

[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' https://cdn.tailwindcss.com https://cdn.jsdelivr.net https://formait-backend.onrender.com; style-src 'self' 'unsafe-inline' https://cdn.jsdelivr.net https://cdn.tailwindcss.com; connect-src 'self' https://formait-backend.onrender.com wss://formait-backend.onrender.com;"

  [[redirects]]
  from = "/inbox"
  to = "/user-inbox.html"
  status = 200